site_name: m5-101 
site_url: https://paulcccccch.github.io/

theme:
  name: cinder

nav:
  - Home: index.md
  - Schedule:
    - Overview: content/schedule.md
    - Week 1 - Introduction: content/week1.md
    - Week 2 - Calculations: content/week2.md
  - Notes:
    - Introduction: 'content/introduction.md'

repo_url: https://github.com/PaulCCCCCCH/m5-101
