site_name: m5-101 
site_url: https://icewould.github.io/
site_author: IceWould Training Team Led by Chonghan Chen
site_description: IceWould Training Hub

theme:
  name: cinder

nav:
  - Home: index.md
  - Schedule: content/schedule.md
  - Notes:
    - Introduction: 'content/introduction.md'

repo_url: https://github.com/IceWould/m5-101
